import type { Metadata } from "next";
import { Work_Sans } from "@next/font/google";

const workSans = Work_Sans({ 
    subsets: ['latin'],
});

import "./globals.css";

export const metadata: Metadata = {
  title: "PSI do Futuro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} bg-salmon`}>{children}</body>
    </html>
  );
}
